// example/demo-vue/src/components/BasicDemo.vue
<template>
  <button @click="handleLoadingClick">toggle loading</button>
  <button @click="handleOptionClick">toggle option type</button>
  <c-base-chart style="width: 100%; height: 400px">
    <c-x-axis type="category" />
    <c-y-axis />
    <c-dataset :source="chartData" :dimensions="dimensions" />
    <c-series type="line" />
    <c-series type="line" />
    <c-series type="line" />
    <c-tooltip trigger="axis" />
    <c-legend />
    <c-method-loading :loading="loading" />
    <c-method-resize :resize="true" />
    <c-event eventName="click" :handler="handleChartClick" />
  </c-base-chart>

  <c-chart style="width: 100%; height: 400px" backgroundColor="rgba(0,0,0,0.1)" :loading="loading" :resize="true">
    <c-x-axis type="category" />
    <c-y-axis />
    <c-dataset :source="chartData" :dimensions="dimensions" />
    <c-series type="line" />
    <c-series type="line" />
    <c-series :options="option" />
    <c-tooltip trigger="axis" />
    <c-legend />
    <c-event eventName="click" :handler="handleChartClick" />
  </c-chart>

  <c-base-chart style="width: 100%; height: 400px" :chartRef="handleChartInit" />
</template>

<script lang="ts">
import { defineComponent, ref, reactive } from "vue";
export default defineComponent({
  name: "BasicDemo",
  setup: () => {
    const dimensions = ["product", "2015", "2016", "2017"];
    const chartData = [
      { product: "Matcha Latte", "2015": 43.3, "2016": 85.8, "2017": 93.7 },
      { product: "Milk Tea", "2015": 83.1, "2016": 73.4, "2017": 55.1 },
      { product: "Cheese Cocoa", "2015": 86.4, "2016": 65.2, "2017": 82.5 },
      { product: "Walnut Brownie", "2015": 72.4, "2016": 53.9, "2017": 39.1 },
    ];

    const loading = ref<boolean>(false);

    const handleLoadingClick = () => {
      loading.value = !loading.value;
    };

    const handleChartClick = (e: any) => {
      console.log("@@@@@@@@@@@@", e);
    };

    const handleChartInit = (chart: any) => {
      chart.setOption({
        legend: {},
        tooltip: { trigger: "axis" },
        xAxis: { type: "category" },
        yAxis: {},
        series: [{ type: "line" }, { type: "line" }, { type: "line" }],
        dataset: { dimensions: dimensions, source: chartData },
      });
    };

    const option = reactive({ type: "line" });

    const handleOptionClick = () => {
      option.type = option.type === "line" ? (option.type = "bar") : (option.type = "line");
    };

    return {
      dimensions,
      chartData,
      loading,
      handleLoadingClick,
      handleChartClick,
      handleChartInit,
      option,
      handleOptionClick,
    };
  },
});
</script>

// example/demo-react/src/component/BasicDemo.tsx
import React, { useState } from "react";
import {
  BaseChart,
  Chart,
  Dataset,
  Event,
  Legend,
  MethodResize,
  Series,
  Tooltip,
  XAxis,
  YAxis,
} from "@echarts-start/react-bridge";

const data = [
  { product: "Matcha Latte", "2015": 43.3, "2016": 85.8, "2017": 93.7 },
  { product: "Milk Tea", "2015": 83.1, "2016": 73.4, "2017": 55.1 },
  { product: "Cheese Cocoa", "2015": 86.4, "2016": 65.2, "2017": 82.5 },
  { product: "Walnut Brownie", "2015": 72.4, "2016": 53.9, "2017": 39.1 },
];

const dimensions = ["product", "2015", "2016", "2017"];

const Demo1 = () => {
  const [loading, setLoading] = useState<boolean>(false);
  return (
    <div style={{ textAlign: "center" }}>
      <a href={"#"} onClick={() => setLoading((prevState) => !prevState)}>
        toggle loading
      </a>
      <Chart style={{ width: "100%", height: 400 }} resize loading={loading}>
        <XAxis type={"category"} />
        <YAxis />
        <Tooltip trigger={"axis"} />
        <Legend />
        <Series type={"line"} />
        <Series type={"line"} />
        <Series type={"line"} />
        <Dataset dimensions={dimensions} source={data} />
        <Event
          eventName={"click"}
          eventHandler={(e) => {
            console.log("click event=", e);
          }}
        />
      </Chart>
    </div>
  );
};

const Demo2 = () => {
  return (
    <BaseChart style={{ width: "100%", height: 400 }}>
      <XAxis type={"category"} />
      <YAxis />
      <Tooltip trigger={"axis"} />
      <Legend />
      <Series type={"line"} />
      <Series type={"line"} />
      <Series type={"line"} />
      <Dataset dimensions={dimensions} source={data} />
      <MethodResize resize />
      <Event
        eventName={"click"}
        eventHandler={(e) => {
          console.log("click event=", e);
        }}
      />
    </BaseChart>
  );
};

const Demo3 = () => {
  return (
    <Chart
      resize
      style={{ width: "100%", height: 400 }}
      chartRef={(chart) => {
        chart.setOption({
          legend: {},
          tooltip: { trigger: "axis" },
          xAxis: { type: "category" },
          yAxis: {},
          series: [{ type: "line" }, { type: "line" }, { type: "line" }],
          dataset: { dimensions, source: data },
        });
      }}
    />
  );
};

export const BasicDemo = () => {
  return (
    <div>
      <div>Chart</div>
      <Demo1 />
      <div>BaseChart</div>
      <Demo2 />
      <div>Chart Ref</div>
      <Demo3 />
    </div>
  );
};
